
/*******************************************************************************
 *
 * File global.hpp
 *
 * Author (2018): Jonas Rylund Glesaaen
 *
 * This software is distributed under the terms of the GNU General Public
 * License (GPL)
 *
 * Global parameters and arrays
 *
 *******************************************************************************/

#ifndef CPP_GLOBAL_HPP
#define CPP_GLOBAL_HPP

#include "internal/function_alias.hpp"

extern "C" {
#include "c_headers/global.h"
}

namespace openqcd {

OPENQCD_GLOBAL_VARIABLE_ALIAS(NPROC0)
OPENQCD_GLOBAL_VARIABLE_ALIAS(NPROC1)
OPENQCD_GLOBAL_VARIABLE_ALIAS(NPROC2)
OPENQCD_GLOBAL_VARIABLE_ALIAS(NPROC3)

OPENQCD_GLOBAL_VARIABLE_ALIAS(L0)
OPENQCD_GLOBAL_VARIABLE_ALIAS(L1)
OPENQCD_GLOBAL_VARIABLE_ALIAS(L2)
OPENQCD_GLOBAL_VARIABLE_ALIAS(L3)

OPENQCD_GLOBAL_VARIABLE_ALIAS(NPROC0_BLK)
OPENQCD_GLOBAL_VARIABLE_ALIAS(NPROC1_BLK)
OPENQCD_GLOBAL_VARIABLE_ALIAS(NPROC2_BLK)
OPENQCD_GLOBAL_VARIABLE_ALIAS(NPROC3_BLK)

OPENQCD_GLOBAL_VARIABLE_ALIAS(NPROC)
OPENQCD_GLOBAL_VARIABLE_ALIAS(VOLUME)
OPENQCD_GLOBAL_VARIABLE_ALIAS(FACE0)
OPENQCD_GLOBAL_VARIABLE_ALIAS(FACE1)
OPENQCD_GLOBAL_VARIABLE_ALIAS(FACE2)
OPENQCD_GLOBAL_VARIABLE_ALIAS(FACE3)
OPENQCD_GLOBAL_VARIABLE_ALIAS(BNDRY)
OPENQCD_GLOBAL_VARIABLE_ALIAS(NSPIN)

OPENQCD_GLOBAL_VARIABLE_ALIAS(cpr)
OPENQCD_GLOBAL_VARIABLE_ALIAS(npr)

OPENQCD_GLOBAL_VARIABLE_ALIAS(ipt)
OPENQCD_GLOBAL_VARIABLE_ALIAS(iup)
OPENQCD_GLOBAL_VARIABLE_ALIAS(idn)
OPENQCD_GLOBAL_VARIABLE_ALIAS(map)

OPENQCD_GLOBAL_FUNCTION_ALIAS(set_lattice_sizes)

} // namespace openqcd

#ifndef CPP_SU3_HPP
#include "su3.hpp"
#endif

#endif /* CPP_GLOBAL_HPP */
