SHELL:=/bin/bash
CC=dpcpp
CFLAGS=-O2 -Wall
LDFLAGS=
INCLUDES=-Iincludes

intel_cpu: CC = dpcpp

nvidia_gpu: CC = clang++
nvidia_gpu: CFLAGS += -fsycl -fsycl-targets=nvptx64-nvidia-cuda

all: intel_cpu nvidia_gpu

intel_cpu: main.c dw_soa_sycl.cpp read_in.c
	module purge;                                                                                     \
	source /usr/local/software/intel/oneapi/2022.1/setvars.sh >/dev/null 2>&1;                        \
    $(CC) $(INCLUDES) $(CFLAGS) $^ -o main.intel_cpu

nvidia_gpu: main.c dw_soa_sycl.cpp read_in.c
	module purge;                                                                                     \
    source /usr/local/software/intel/oneapi/2022.1/setvars.sh >/dev/null 2>&1;                        \
    module use /usr/local/software/spack/spack-modules/dpcpp-cuda-20220220/linux-centos8-x86_64_v3/;  \
    module load dpcpp;                                                                                \
    module load gcc/11.2.0;                                                                           \
    $(CC) $(INCLUDES) $(CFLAGS) $^ -o main.nvidia_gpu

clean:
	rm -f *.o a.out 2>/dev/null main.*_?pu

logclean:
	rm -rf logs_of_job_output_and_error/*
