name: C/C++ CI

on:
  push:
    branches: [ arc_dev ]
  pull_request:
    branches: [ arc_dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout LFS objects
      run: |
        git lfs pull --include=data/* --exclude=tests/stout_smearing/configurations/*

    - name: Setup OneAPI
      run: |
        # Following the instructions in
        # https://www.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-linux/top/installation/install-using-package-managers/apt.html#apt
        # download the key to system keyring
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
        | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null

        # add signed entry to apt sources and configure the APT client to use Intel repository:
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt -y update

    - name: Install OneAPI
      # Following the instructions in
      # https://neelravi.com/post/oneapi-github-workflow/
      run: |
        sudo apt install -y intel-oneapi-common-vars
        sudo apt install -y intel-oneapi-compiler-dpcpp-cpp

    - name: Setup hipSYCL
      # Following the instructions in
      # https://github.com/illuhad/hipSYCL/blob/develop/install/scripts/README.md#installing-from-repositories
      run: |
        export DEBIAN_FRONTEND=noninteractive
        echo "deb http://repo.urz.uni-heidelberg.de/sycl$1/deb/ ./focal main" | sudo tee /etc/apt/sources.list.d/hipsycl.list
        wget -q -O - http://repo.urz.uni-heidelberg.de/sycl/hipsycl.asc | sudo apt-key add -
        sudo apt -y update

    - name: Install hipSYCL
      run: |
        sudo apt -y install libtinfo5
        sudo apt -y install hipsycl-nightly
        echo "/opt/hipSYCL/bin" >> $GITHUB_PATH
        
    - name: Make OneAPI
      working-directory: ${{github.workspace}}/tests/cuda2/dpct_output
      run: |
        . /opt/intel/oneapi/setvars.sh
        make oneapi_intel_cpu
      env:
        CC: dpcpp
        CXX: dpcpp
        
    - name: Make hipSYCL
      working-directory: ${{github.workspace}}/tests/cuda2/dpct_output
      run: |
        make hip_omp_cpu
      env:
        HIPSYCL_PLATFORM: cpu
        CC: syclcc
        CXX: syclcc

    - name: Test-16 OneAPI
      working-directory: ${{github.workspace}}/tests/cuda2/dpct_output
      run: |
        . /opt/intel/oneapi/setvars.sh
        ./main.oneapi_intel_cpu 16 16 16 16 ${{github.workspace}}/data

    - name: Test-16 hipSYCL
      working-directory: ${{github.workspace}}/tests/cuda2/dpct_output
      run: |
        ./main.hip_omp_cpu 16 16 16 16 ${{github.workspace}}/data


    # - name: Test-32
    #   working-directory: ${{github.workspace}}/tests/cuda2/dpct_output
    #   run: ./main 32 32 32 32 ${{github.workspace}}/data
